version: "3.8"
services:
  app:
    build:
      context: ./ 
      dockerfile: Dockerfile.production  # 本番用のDockerfileを指定
    command: sh -c "yarn start"  # 開発環境用のコマンドから本番用のコマンドに変更
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}  # .env から本番用のデータベースURLを読み込む
    ports:
      - '5173:5173'
      - '5555:5555'
    volumes:
      - .:/app
      - ./prisma:/app/prisma
    user: 0:0
